### ISSUE TITLE
Unreachable repositories

### ISSUE THREAD

**Issue by conde-ISR-UC-PT** [ctu-vras/robingas_mission_gazebo#1]
While running 
`wstool up -j 4`

it get stuck in a never ending loop:
[augmented_robot_trackers,cras_gps_odom,cras_imu_tools] still active
[augmented_robot_trackers,cras_gps_odom,cras_imu_tools] still active
[augmented_robot_trackers,cras_gps_odom,cras_imu_tools] still active
[augmented_robot_trackers,cras_gps_odom,cras_imu_tools] still active
[augmented_robot_trackers,cras_gps_odom,cras_imu_tools] still active
[augmented_robot_trackers,cras_gps_odom,cras_imu_tools] still active

performing  `wstool update`  I get the following messages:

/catkin_ws/src$ wstool update
[augmented_robot_trackers] Fetching git@gitlab.fel.cvut.cz:cras/subt/common/augmented_robot_trackers.git (version master) to /home/rob/catkin_ws/src/augmented_robot_trackers
Cloning into '/home/rob/catkin_ws/src/augmented_robot_trackers'...
git@gitlab.fel.cvut.cz's password: 
Permission denied, please try again.
git@gitlab.fel.cvut.cz's password: 

Theferore I went through dependencies.rosinstall, and I realize it is not possible to access the following git repositories:

```
- git:
    local-name: cras_gps_odom
    uri: git@gitlab.fel.cvut.cz:cras/subt/common/cras_imu_tools.git
    version: master
```

```
- git:
    local-name: augmented_robot_trackers
    uri: git@gitlab.fel.cvut.cz:cras/subt/common/augmented_robot_trackers.git
    version: master
```

```
- git:
    local-name: cras_imu_tools
    uri: git@gitlab.fel.cvut.cz:cras/subt/common/cras_imu_tools.git
    version: master
```

Can you please put them publicly available in github?
